### ISSUE TITLE
Interaction with TagBar causing slow responsiveness in large python project

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [akinsho/nvim-bufferline.lua#101] opened 2021-05-17 15:24 UTC
my config is
```python
require('bufferline').setup {
    options = {
        numbers = 'buffer_id',
        number_style = '',
        mappings = false,
        diagnostics = false,

        indicator_icon = '|',
        buffer_close_icon = 'x',
        close_icon = 'x',
        modified_icon = '~',
        left_trunc_marker = '<',
        right_trunc_marker = '>',

        offsets = {
            {filetype = "NvimTree", text = "Explorer", text_align = "center"},
            {filetype = "tagbar", text = 'Tagbar', text_align = 'center'},
        },

        show_tab_indicators = true,
        show_buffer_icons = true,
        show_buffer_close_icons = false,
        show_close_icon = false,
        enforce_regular_tabs = false,
        always_show_bufferline = true,
        separator_style = "thin",
    }
}
```

and other installed plugins include 
```lua
    'airblade/vim-rooter'  
    'jiangmiao/auto-pairs' 
    'tpope/vim-fugitive' 
    'majutsushi/tagbar'   
    'christoomey/vim-tmux-navigator'
    'tpope/vim-eunuch'
    'godlygeek/tabular'
    'b3nj5m1n/kommentary'
    'akinsho/nvim-bufferline.lua'
    'lewis6991/gitsigns.nvim'
    'kyazdani42/nvim-tree.lua'
    'neovim/nvim-lspconfig'
    'hrsh7th/nvim-compe'
    'onsails/lspkind-nvim'
    'nvim-treesitter/nvim-treesitter'
    'junegunn/fzf.vim'
    'junegunn/fzf'
    'morhetz/gruvbox'
    'relastle/bluewery.vim'
    'flazz/vim-colorschemes'
    'shaunsingh/moonlight.nvim'
```

i have diagnosed the cause of slow responsiveness to this plugin, by uninstalling / reinstalling each plugin one by one (other than color schemes). Even in default config, this plugin is causing me slow responsiveness. I have tested this on a big python project, and the uninstalling/disabling this plugin makes the project usable in vim, otherwise not.

**Comment by ViRu-ThE-ViRuS** [comment] 2021-05-17 15:24
please suggest how i can better diagnose this issue

**Comment by akinsho** [comment] 2021-05-17 16:11
@ViRu-ThE-ViRuS I need a bit more information to help diagnose this because based on what you've said I wouldn't really know where to start.

### Step 1
When you say you are sure it comes from this plugin have you tried running a minimal init.vim or lua e.g.
*no other plugins, no other settings* just loading the plugin (if you use packer make sure to delete packer compiled) if you use start plugins via `:h packages` make sure they aren't loaded using `nvim -u <path/to/minimal_init.vim --noplugin`.
When you say slow  what do you mean? is it slow all the time? is it slow on a specific event like insert enter?

### Step 2
Once you've verified that there is no other possible cause, can you report back, how big is a big python project, tbh this plugin doesn't really care about how big a project is since it isn't reading a users project at all it only reads the list of listed buffers (this is just so I have an idea of if I can reproduce this in a similarly large project). So a good start is how many buffers you have visible, how many listed ones are available are there in your vim instance?

Tbh I have never had a report like this so I don't really know how it's possible (not to say that it isn't I just can't think of *how it could be*. Ultimately this plugin is only operating on a list of like 100s of buffers or something at a push using lua which is very fast not sure if people have more buffers open than that really but still should never lead to lagging.

Also if you could share a screen recording of the lag that might be helpful as well

**Comment by ViRu-ThE-ViRuS** [comment] 2021-05-17 16:25
@akinsho thanks for getting back to me with such detail, ill go through what you recommend, and try to help narrow it down :)

**Comment by tmerse** [comment] 2021-05-18 07:55
Came here after I noticed something similar. Did a quick divide-and-conquer of my `init.vim` to find out that (at least for me) `preservim/tagbar` seems to have some heisenbugesque interaction with this plugin, affecting overall responsiveness.

```
  let g:tagbar_left = 1
  let g:tagbar_autoclose = 1
  let g:tagbar_autoshowtag = 1
  let g:tagbar_compact = 1 "enable to show helptext
  let g:tagbar_sort = 0 " sort by tag order
  " TODO: cannot read from /tmp (:TagbarDebug)
  " Fixes: https://github.com/preservim/tagbar/issues/568
  " Could this affect bufferline responsiveness? https://github.com/akinsho/nvim-bufferline.lua/issues/101
  let g:tagbar_use_cache = 0
  let g:tagbar_ctags_bin = "/snap/bin/ctags"
  " let g:tagbar_ctags_bin = "/usr/bin/ctags"
```

When I use another – or no tab/buffer plugin, there is no noticable inputlag. Once I enable tabline, responsiveness degrades. After setting `let g:tagbar_use_cache = 1` or disabling the tagbar plugin, everything runs smooth again. I can't imagine how those plugins would interact but that was just my observation. Maybe you use something similar @ViRu-ThE-ViRuS ?

**Comment by ViRu-ThE-ViRuS** [comment] 2021-05-18 09:03
@tmerse i tested it out:
- adding `let g:tagbar_use_cache=1` to config, nothing changed... still unresponsive. I checked in the help, and this option is anyways 1 by default
- disabling the `preservim/tagbar' plugin solved the issue, no slowing down in responsiveness

@akinsho another interesting thing i noticed is that the same configuration (with `preervim/tagbar`) works completely fine on my MacOS system, and even on a remote Ubuntu 20 LTS vm through ssh, on the same project files. I made sure to match neovim version, lsp server version, plugin versions, and virtualenv setup. Its just an issue on my Ubuntu 20 LTS PC (just a HDD).

**Comment by akinsho** [comment] 2021-05-20 13:58
Sorry both I'm a bit swamped atm so can't really dig into this especially given I don't really use/nor am I familiar with tagbar really. Seems it's had quite a long history though so I wouldn't be surprised if somewhere along the way it picked up some code that affects the buffer list or the tabline.

If you have `offsets` enabled can you try without and see if that helps, then maybe try and disable other features of bufferline to see if it comes down to a specific option. If not then there might be an interaction, sounds like it would need some digging into the logic of tagbar to figure out how and why this way be happening, but as I mentioned I don't really have the bandwidth for that atm.

**Comment by tmerse** [comment] 2021-05-20 14:56
@akinsho no worries. I think nobody should expect anything like that at all. Plus I don't really use tagbar anymore. Thanks for providing this nice plugin!

**Comment by akinsho** [comment] 2021-07-14 15:38
Gonna close this out since it isn't really actionable on my side. Hopefully anyone who encounters this issue this as a guide. Thanks for investigating.

**Closed by akinsho** 2021-07-14 15:38 UTC
