### ISSUE TITLE
How to make it only open a new tab when chose open in Tab 

### ISSUE THREAD

**Issue by letieu** [akinsho/nvim-bufferline.lua#129] opened 2021-06-26 06:58 UTC
I want only create a new tab when i need ( choose open new Tab in FZF or in NvimTree). When using this plugin, i can't config it work for me, it create a new Tab when i open a file, not when create new Buffer. So it make very much tab and it's not necessary and messy. 

And can you tell me how to close a Tab by command or something isn't Mouse ?.  `:q` make quit buffer, not close a Tab

**Comment by letieu** [comment] 2021-06-26 07:46
Now for close Tab and reopen NvimTree, i have a function like this

**Comment by akinsho** [comment] 2021-06-26 08:49
@letieu I'm sorry, but I don't understand at all what the issue is. I think you are mixing up tabs and buffers, maybe.
>  it create a new Tab when i open a file, not when create new Buffer

When you open a file *vim creates a buffer* this plugin sees that vim has done that and shows the buffer, you can't pick and choose whether vim will create a buffer. If you open a file, vim *will* create a buffer and this plugin will show it.

You can use the filter key to create a filter function if there are only some files you want to show, but I'll leave it to you to read the README and figure that out.

To close a buffer (since the plugin mainly deals with buffers) there are loads of native vim ways that don't have anything to do with this plugin e.g. `:bdelete`

**Comment by akinsho** [comment] 2021-06-29 07:33
I've not got any more input on this and this issue isn't very clear/actionable on my end otherwise, so I'm going to close this out. Feel free to add in more info in the future, and we can discuss/re-open if necessary.

**Closed by akinsho** 2021-06-29 07:33 UTC
